### ISSUE TITLE
What are you working on?

### ISSUE THREAD

**Issue by Xyncgas** [pomonella01/Loom#10]
I am curious what you are working on, maybe I can play with you

**Comment by pmnlla** [comment]
As of now I'm working more on system administration and less on software engineering. 
I do a lot more internal prototype stuff under lilylab that can't be released either. I might revisit the idea of an easy to use minecraft mod manager later, but that's not something that concerns me at the moment with the way this project died.

In terms of games, that's a part of my life I like to keep private between friends et al.

**Comment by pmnlla** [comment]
Closing as stale
